mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启之后可以在状态栏看到sql语句
#  global-config:
#    db-config:
#      table-prefix: t_

spring:
  redis:
    host: localhost #172.18.96.224
    port: 6379
#    host: minsapp-aliyun-redis.redis.rds.aliyuncs.com
#    username: user_luohaojun
#    password: 2022gdutLUOHAOJUN
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/minsappofteachingforchildren?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

#    username: root
#    password: admin
#    url: jdbc:mysql://106.53.151.173:3306/minsappofteachingforchildren?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888

dns: http://localhost:8888/